[mypy]
ignore_missing_imports = True
exclude = (?x)(
    ^migrations/
    | ^venv/
    | ^\.venv/
    | ^venv2/
  )
disable_error_code = call-arg, attr-defined, union-attr, assignment, arg-type, return-value, dict-item, annotation-unchecked
