"""initial_schema

Revision ID: 057223d89cd2
Revises: 
Create Date: 2026-08-30 17:47:33.645095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '057223d89cd2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorization_capabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capability_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('buyer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('merchant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('approval_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount_inr', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nonce', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CONSUMED', 'EXPIRED', 'REVOKED', name='capabilitystatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoke_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorization_capabilities_buyer_id'), 'authorization_capabilities', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_authorization_capabilities_capability_id'), 'authorization_capabilities', ['capability_id'], unique=True)
    op.create_index(op.f('ix_authorization_capabilities_merchant_id'), 'authorization_capabilities', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_authorization_capabilities_transaction_id'), 'authorization_capabilities', ['transaction_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('BUYER', 'MERCHANT_OWNER', 'MERCHANT_ADMIN', 'MERCHANT_OPERATOR', 'PLATFORM_ADMIN', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'PENDING_VERIFICATION', name='userstatus'), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webhook_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('processing_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_link_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_provider_event_id'), 'webhook_events', ['provider_event_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_transaction_id'), 'webhook_events', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_webhook_id'), 'webhook_events', ['webhook_id'], unique=True)
    op.create_table('buyer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('daily_limit_inr', sa.Integer(), nullable=False),
    sa.Column('per_transaction_auto_limit_inr', sa.Integer(), nullable=False),
    sa.Column('approval_threshold_inr', sa.Integer(), nullable=False),
    sa.Column('blocked_categories', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('blocked_merchants', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_profiles_user_id'), 'buyer_profiles', ['user_id'], unique=True)
    op.create_table('merchant_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'OPERATOR', name='merchantuserrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_users_merchant_id'), 'merchant_users', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_merchant_users_user_id'), 'merchant_users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merchant_users_user_id'), table_name='merchant_users')
    op.drop_index(op.f('ix_merchant_users_merchant_id'), table_name='merchant_users')
    op.drop_table('merchant_users')
    op.drop_index(op.f('ix_buyer_profiles_user_id'), table_name='buyer_profiles')
    op.drop_table('buyer_profiles')
    op.drop_index(op.f('ix_webhook_events_webhook_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_transaction_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_provider_event_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_authorization_capabilities_transaction_id'), table_name='authorization_capabilities')
    op.drop_index(op.f('ix_authorization_capabilities_merchant_id'), table_name='authorization_capabilities')
    op.drop_index(op.f('ix_authorization_capabilities_capability_id'), table_name='authorization_capabilities')
    op.drop_index(op.f('ix_authorization_capabilities_buyer_id'), table_name='authorization_capabilities')
    op.drop_table('authorization_capabilities')
    # ### end Alembic commands ###
