"""initial_schema

Revision ID: 057223d89cd2
Revises:
Create Date: 2026-08-30 17:47:33.645095

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '057223d89cd2'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('correlation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('buyer_intent', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parsed_constraints', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('merchant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('merchant_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount_inr', sa.Integer(), nullable=True),
    sa.Column('candidates_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('selected_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('policy_result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('policy_reason_codes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('approval_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approved_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('razorpay_payment_link_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('razorpay_payment_link_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('razorpay_order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('razorpay_payment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'CANCELLED', 'PAYMENT_LINK_CREATED', 'PAYMENT_SUCCESS', 'PAYMENT_FAILED', 'PAYMENT_UNKNOWN', 'VERIFIED_SUCCESS', 'VERIFIED_FAILED', 'RECEIPT_ISSUED', 'RECOVERY_PROPOSED', name='transactionstate'), nullable=False),
    sa.Column('recovery_action', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('failure_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_correlation_id'), 'transactions', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('merchant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price_inr', sa.Integer(), nullable=False),
    sa.Column('inventory_count', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=False),
    sa.Column('delivery_sla_days_min', sa.Integer(), nullable=False),
    sa.Column('delivery_sla_days_max', sa.Integer(), nullable=False),
    sa.Column('return_policy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('merchant_rating', sa.Float(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_merchant_id'), 'products', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=False)
    op.create_table('merchants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('max_autonomous_spend_inr', sa.Integer(), nullable=False),
    sa.Column('approval_threshold_inr', sa.Integer(), nullable=False),
    sa.Column('restricted_categories', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('refund_authority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('arm_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('arm_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchants_merchant_id'), 'merchants', ['merchant_id'], unique=True)
    op.create_table('idempotency_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_idempotency_key')
    )
    op.create_index(op.f('ix_idempotency_records_idempotency_key'), 'idempotency_records', ['idempotency_key'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('correlation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reason_codes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('policy_result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('next_state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_actor'), 'audit_events', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_events_correlation_id'), 'audit_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_events_event_id'), 'audit_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_transaction_id'), 'audit_events', ['transaction_id'], unique=False)
    op.create_table('authorization_capabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capability_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('buyer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('merchant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('approval_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount_inr', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nonce', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CONSUMED', 'EXPIRED', 'REVOKED', name='capabilitystatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoke_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorization_capabilities_buyer_id'), 'authorization_capabilities', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_authorization_capabilities_capability_id'), 'authorization_capabilities', ['capability_id'], unique=True)
    op.create_index(op.f('ix_authorization_capabilities_merchant_id'), 'authorization_capabilities', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_authorization_capabilities_transaction_id'), 'authorization_capabilities', ['transaction_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('BUYER', 'MERCHANT_OWNER', 'MERCHANT_ADMIN', 'MERCHANT_OPERATOR', 'PLATFORM_ADMIN', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'PENDING_VERIFICATION', name='userstatus'), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webhook_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('processing_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_link_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_provider_event_id'), 'webhook_events', ['provider_event_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_transaction_id'), 'webhook_events', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_webhook_id'), 'webhook_events', ['webhook_id'], unique=True)
    op.create_table('buyer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('daily_limit_inr', sa.Integer(), nullable=False),
    sa.Column('per_transaction_auto_limit_inr', sa.Integer(), nullable=False),
    sa.Column('approval_threshold_inr', sa.Integer(), nullable=False),
    sa.Column('blocked_categories', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('blocked_merchants', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_profiles_user_id'), 'buyer_profiles', ['user_id'], unique=True)
    op.create_table('merchant_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'OPERATOR', name='merchantuserrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_users_merchant_id'), 'merchant_users', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_merchant_users_user_id'), 'merchant_users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('correlation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('buyer_intent', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parsed_constraints', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('merchant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('merchant_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount_inr', sa.Integer(), nullable=True),
    sa.Column('candidates_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('selected_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('policy_result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('policy_reason_codes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('approval_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approved_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('razorpay_payment_link_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('razorpay_payment_link_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('razorpay_order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('razorpay_payment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'CANCELLED', 'PAYMENT_LINK_CREATED', 'PAYMENT_SUCCESS', 'PAYMENT_FAILED', 'PAYMENT_UNKNOWN', 'VERIFIED_SUCCESS', 'VERIFIED_FAILED', 'RECEIPT_ISSUED', 'RECOVERY_PROPOSED', name='transactionstate'), nullable=False),
    sa.Column('recovery_action', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('failure_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_correlation_id'), 'transactions', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('merchant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price_inr', sa.Integer(), nullable=False),
    sa.Column('inventory_count', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=False),
    sa.Column('delivery_sla_days_min', sa.Integer(), nullable=False),
    sa.Column('delivery_sla_days_max', sa.Integer(), nullable=False),
    sa.Column('return_policy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('merchant_rating', sa.Float(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_merchant_id'), 'products', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=False)
    op.create_table('merchants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('max_autonomous_spend_inr', sa.Integer(), nullable=False),
    sa.Column('approval_threshold_inr', sa.Integer(), nullable=False),
    sa.Column('restricted_categories', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('refund_authority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('arm_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('arm_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchants_merchant_id'), 'merchants', ['merchant_id'], unique=True)
    op.create_table('idempotency_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_idempotency_key')
    )
    op.create_index(op.f('ix_idempotency_records_idempotency_key'), 'idempotency_records', ['idempotency_key'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('correlation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reason_codes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('policy_result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('next_state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_actor'), 'audit_events', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_events_correlation_id'), 'audit_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_events_event_id'), 'audit_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_transaction_id'), 'audit_events', ['transaction_id'], unique=False)
    op.drop_index(op.f('ix_merchant_users_user_id'), table_name='merchant_users')
    op.drop_index(op.f('ix_merchant_users_merchant_id'), table_name='merchant_users')
    op.drop_table('merchant_users')
    op.drop_index(op.f('ix_buyer_profiles_user_id'), table_name='buyer_profiles')
    op.drop_table('buyer_profiles')
    op.drop_index(op.f('ix_webhook_events_webhook_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_transaction_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_provider_event_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_authorization_capabilities_transaction_id'), table_name='authorization_capabilities')
    op.drop_index(op.f('ix_authorization_capabilities_merchant_id'), table_name='authorization_capabilities')
    op.drop_index(op.f('ix_authorization_capabilities_capability_id'), table_name='authorization_capabilities')
    op.drop_index(op.f('ix_authorization_capabilities_buyer_id'), table_name='authorization_capabilities')
    op.drop_table('authorization_capabilities')
    # ### end Alembic commands ###
